# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Hj3USVHchDuksyZ-oV828Y_HBxlFRQi
"""

'''a=input("Enter a character")
if a in 'AEIOU' or 'aeiou':
  print("Vowel")
else:
  print("Consonant")'''
'''
a=int(input("Enter a number"))
b=int(input("Enter a number"))
c=int(input("Enter a number"))
if a>b and a>c:
  print(a,"is greater")
elif b>a and b>c:
  print(b,"is greater")
else:
  print(c,"is greater")'''
'''
l=[1,2,3,4,5]
a=int(input("Enter any index number"))
if l[a]%2==0:
  print("Even")
else:
  print("Odd")'''
'''
def printnum():
  print("Hello Number")
printnum()'''
'''
def name():
  print("Eshaan Singh Deo")
name()'''

'''def num():
  if num%2==0:
    print("Even")
  else:
    print("Odd")
num()
''''''
def func(list,index):
  if list[index]%2==0:
    print("Even")
  else:
    print("Odd")
list=[1,2,3,4,5]
index=int(input("Enter any index number"))
func(list,index)
'''
'''
def func(id):
  if '@' in id and '.com' in id:
    print("Valid")
  else:
    print("Invalid")
id=input("Enter a email id")
func(id)
''''''
def sq(list):
  for i in list:
    print(i**2)
list=[1,2,3]
sq(list)'''
'''
def func(list1,list2):
  for i in list1:
    list2.append(i)
  for j in list2:
    print(j,end='\n')
list1=[1,2,3]
list2=[4,5,6]
func(list1,list2)'''
'''
def func(list):
  for i in list:
    if list[i]%2==0:
      print(i,end='\n')
list=[1,2,3,4,5]
func(list)''''''
def sq(x):
  print(x*x)
a=lambda x:x*x
print(a(10))'''
'''
# Simple lambda calculator
calculator = {
    '+': lambda x, y: x + y,
    '-': lambda x, y: x - y,
    '*': lambda x, y: x * y,
    '/': lambda x, y: "Error: Division by zero" if y == 0 else x / y
}

# User input and operation
x = float(input("Enter first number: "))
y = float(input("Enter second number: "))
op = input("Enter operation (+, -, *, /): ")

result = calculator.get(op, lambda x, y: "Invalid operation")(x, y)
print(f"Result: {result}")
'''
'''
def even():
    even= [x for x in range(0, 51) if x % 2 == 0]
    print(even)

even()
'''

def func(list1,list2):
  for i in list1:
    for j in list2:
      if i==j:
        print(list1[i],list2[j])
list1=["Abh","Pandey","Alok"]
list2=[100,200,300]
func(list1,list2)

def func(list1, list2):
    for i in range(len(list1)):
        for j in range(len(list2)):
            if i == j:
                print(list1[i], list2[j])

list1 = ["Abh", "Pandey", "Alok"]
list2 = [100, 200, 300]
func(list1, list2)



def func(list):
  for i in range(1, len(list)):
    if list[i]>list[i-1]:
      continue
    elif list[i]<list[i-1]:
      list[i]=list[i-1]
  print(list)
list=[1,3,5,7,4]
func(list)

d={1:23,2:34}
e=eval(input("Enter dictionary"))