# Generated by Django 5.2.5 on 2025-08-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(max_length=100)),
                ('account_number', models.IntegerField(db_default=0, unique=True)),
                ('ifsc_code', models.CharField(max_length=11, unique=True)),
            ],
        ),
    ]
