# Generated by Django 5.2.5 on 2025-08-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=100)),
                ('moviegenre', models.CharField(max_length=100)),
                ('movieyear', models.IntegerField()),
            ],
        ),
    ]
